name: check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    name: Run MELPA checks
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 29.1
          - 29.2
          - 29.3
          - release-snapshot
        include:
          - emacs_version: snapshot
          - ignore_warnings: false
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Setup Emacs
          uses: purcell/setup-emacs@master
          with:
            version: ${{ matrix.emacs_version }}
        - name: Run MELPA checks on package
          uses: leotaku/elisp-check@master
          with:
            check: melpa
            file: '*.el'
            ignore_warnings: false
            warnings_as_errors: false
